# Generated by Django 3.1.3 on 2020-11-20 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_no', models.AutoField(primary_key=True, serialize=False)),
                ('date_confirmed', models.DateField()),
                ('local_or_imported', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Geodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('Xcoord', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Ycoord', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_name', models.CharField(max_length=200)),
                ('hkid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus_name', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=200)),
                ('max_infect_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=200)),
                ('date_to', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=200)),
                ('case_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.case')),
                ('geodata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.geodata')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.virus'),
        ),
    ]
