# Generated by Django 3.1.3 on 2020-11-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201121_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virus', to='backend.virus'),
        ),
        migrations.AlterField(
            model_name='visited',
            name='case_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='backend.case'),
        ),
        migrations.AlterField(
            model_name='visited',
            name='geodata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='backend.geodata'),
        ),
    ]
