# Generated by Django 3.1.3 on 2020-11-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201121_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.patient'),
        ),
        migrations.AlterField(
            model_name='case',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.virus'),
        ),
        migrations.AlterField(
            model_name='visited',
            name='case_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.case'),
        ),
        migrations.AlterField(
            model_name='visited',
            name='geodata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.geodata'),
        ),
    ]
