# Generated by Django 3.1.3 on 2020-11-21 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201121_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hkid',
            field=models.CharField(default=uuid.uuid1, max_length=10, primary_key=True, serialize=False),
        ),
    ]
