# Generated by Django 3.1.3 on 2020-11-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201121_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visited',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visited',
            name='date_to',
            field=models.DateField(),
        ),
    ]
